### ISSUE TITLE
created 3 files and your code doesn't run as-is

### ISSUE THREAD

**Issue by thegleek** [SuyashD95/Advent-of-Code-2018#2]
`$ python day3-p2.py

Traceback (most recent call last):
  File "day3-p2.py", line 35, in <module>
    fabric = Matrix(1000, 1000)
  File "/home/anonymous/aoc-2018/day3matrix.py", line 5, in __init__
    self.matrix = Matrix.__createMatrix(self.rows, self.cols)
TypeError: unbound method __createMatrix() must be called with Matrix instance as first argument (got int instance instead)
`

**Comment by SuyashD95** [comment]
First of all, I am so sorry for not contacting you (@thegleek) earlier... Since I don't have access to your code, I am not sure whether my answer solves your problem or not...

But unfortunately, I am unable to recreate the problem on my side... In my computer (as well as on my father's pc), it is running absolutely fine...

Anyways, after reading about the compilation error (TypeError: unbound method), **I have made certain changes in the code which I believe will solve your issue... Make the following changes in the code of the 'Matrix' class...**

```
class Matrix(object):
    def __init__(self, row_size, col_size):
        self.cols = col_size
        self.rows = row_size
        
        # Added self as a reference to the current object which is calling the __createMatrix method
        self.matrix = Matrix.__createMatrix(self, self.rows, self.cols)  ## Line 5 changed.

    # Changed the signature of __createMatrix() method  
    def __createMatrix(self, rows, cols):  ## Line 7 changed
        matrix = []
        for row in range(rows):
            matrix.append([])
            for col in range(cols):
                matrix[row].append(0)
        return matrix
```

Will wait for your answer to know the outcome of this workaround... I do hope that this issue has been resolved now...
